PROFESSION_ANY      = 0
PROFESSION_PRIMARY  = 1
PROFESSION_UNLOCKED = 2

REWARD_GOLD       = 0  # G
REWARD_ITEMS      = 1  # I
REWARD_SKILLS     = 2  # S
REWARD_POINTS     = 3  # P
REWARD_ATTRIB     = 4  # A
REWARD_RANK       = 5  # R
REWARD_FACTION    = 6  # F
REWARD_ZAISHEN    = 7  # Z
REWARD_HEROES     = 8  # H
REWARD_PROFESSION = 9  # 2
REWARD_MAX        = 10

TREE_TYPE_AREA     = 0
TREE_TYPE_CAMPAIGN = 1
TREE_TYPE_MISSIONS = 2
TREE_TYPE_SKILLS   = 3

WIKI_URL = "https://wiki.guildwars.com/wiki/"
